# -*- coding: utf-8 -*-
"""Bank_Transaction_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flbYmB3yrjvOt7SmsIF0C9EwjcWewJhh
"""

from google.colab import files

print("Please select the 'bank_transaction_analysis.csv' file to upload.")
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

import pandas as pd

df = pd.read_csv('bank_transaction_analysis.csv')

df.head()

"""Data Summary"""

df.info()
df.describe()

"""Fraud Analysis"""

fraud=df[df['Fraud_Flag']=="Yes"]

print(fraud.shape)

"""Branch Revenue"""

branch=df.groupby('Branch_Name')['Amount'].sum()

print(branch)

"""Top Customers"""

top=df.groupby('Customer_ID')['Amount'].sum()

top.sort_values(ascending=False).head(10)

"""Monthly Trend"""

df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'])

monthly=df.groupby(
df['Transaction_Date'].dt.month
)['Amount'].sum().reset_index()

monthly

print(df['Transaction_Date'].head(10))
print(df['Transaction_Date'].dtype)

"""Visualization"""

import matplotlib.pyplot as plt

monthly = df.groupby(
    df['Transaction_Date'].dt.month
)['Amount'].sum()

plt.figure(figsize=(10, 5))
monthly.plot(marker='o')

plt.title('Monthly Transactions')
plt.xlabel('Month')
plt.ylabel('Transaction Amount')
plt.grid(True)

plt.show()

"""Fraud Chart"""

fraud_count=df['Fraud_Flag'].value_counts()

fraud_count.plot(kind='bar')

plt.show()

"""Transaction Statistics"""

import numpy as np

amounts = df['Amount'].values

print("Average Transaction:", np.mean(amounts))
print("Median Transaction:", np.median(amounts))
print("Maximum Transaction:", np.max(amounts))
print("Minimum Transaction:", np.min(amounts))
print("Standard Deviation:", np.std(amounts))

"""Risk Score Analysis"""

risk_scores = df['Risk_Score'].values

print("Average Risk Score:", np.mean(risk_scores))
print("95th Percentile:", np.percentile(risk_scores,95))

"""Outlier Detection (High-Value Transactions)"""

# q1 = np.percentile(df['Amount'],25)
# q3 = np.percentile(df['Amount'],75)

# iqr = q3 - q1

# upper_limit = q3 + 1.5 * iqr

# outliers = df[df['Amount'] > upper_limit]

# print("Outlier Transactions:", len(outliers)) ----> op: Outlier Transactions: 0

q1 = np.percentile(df['Amount'], 25)
q3 = np.percentile(df['Amount'], 75)

iqr = q3 - q1

upper_limit = q3 + 1.5 * iqr

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)
print("Upper Limit:", upper_limit)
print("Maximum Amount:", df['Amount'].max())

"""Customer Segmentation"""

conditions = [
    df['Amount'] < 5000,
    (df['Amount'] >= 5000) & (df['Amount'] < 20000),
    df['Amount'] >= 20000
]

segments = ['Low','Medium','High']

df['Spending_Category'] = np.select(
    conditions,
    segments,
    default='Unknown'
)
print(df[['Amount', 'Spending_Category']].head(10))

"""Fraud Threshold Calculation"""

threshold = np.percentile(df['Amount'],99)

suspicious = df[df['Amount'] > threshold]

print(suspicious[['Transaction_ID','Amount']])