# -*- coding: utf-8 -*-
"""Bank_Transaction_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1flbYmB3yrjvOt7SmsIF0C9EwjcWewJhh
"""

from google.colab import files

print("Please select the 'bank_transaction_analysis.csv' file to upload.")
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

import pandas as pd

df = pd.read_csv('bank_transaction_analysis.csv')

df.head()

"""Data Summary"""

df.info()
df.describe()

"""Fraud Analysis"""

fraud=df[df['Fraud_Flag']=="Yes"]

print(fraud.shape)

"""Branch Revenue"""

branch=df.groupby('Branch_Name')['Amount'].sum()

print(branch)

"""Top Customers"""

top=df.groupby('Customer_ID')['Amount'].sum()

top.sort_values(ascending=False).head(10)

"""Monthly Trend"""

df['Transaction_Date']=pd.to_datetime(df['Transaction_Date'])

monthly=df.groupby(
df['Transaction_Date'].dt.month
)['Amount'].sum().reset_index()

monthly

print(df['Transaction_Date'].head(10))
print(df['Transaction_Date'].dtype)

"""Visualization"""

import matplotlib.pyplot as plt

monthly = df.groupby(
    df['Transaction_Date'].dt.month
)['Amount'].sum()

plt.figure(figsize=(10, 5))
monthly.plot(marker='o')

plt.title('Monthly Transactions')
plt.xlabel('Month')
plt.ylabel('Transaction Amount')
plt.grid(True)

plt.show()

"""Fraud Chart"""

fraud_count=df['Fraud_Flag'].value_counts()

fraud_count.plot(kind='bar')

plt.show()